######################
### DATA TO MODIFY ###
######################
##### Input files #####
# fastq files to analyse (leave r2 quotes empty if unpaired)
r1: "/mnt/beegfs/etempez/remapping/donnees_illumina/NG-24463_kefirba_1.fastq.gz"
r2: "/mnt/beegfs/etempez/remapping/donnees_illumina/NG-24463_kefirba_2.fastq.gz"

# species folder : should only contain <speciesname>.fa or <speciesname>.fasta file for each species
folder_species: "/mnt/beegfs/etempez/remapping/genome"


##### Output infos #####
# output folder (leave empty quotes if you want the output in the folder from which you are launching the snakemake command line)
output_folder: "/mnt/beegfs/etempez/remapping/benchmark/standard/kBA/"
# build name : name of the metagenome version
build_name: "lib_mcf"


##### Configuration #####
# name of folder with all .yml files + the metagenome_ncbi_id.txt file
config_folder: "/trinity/home/etempez/remapping_scripts/config_files"


##### Bowtie and Kraken #####
# should we use Bowtie2 for mapping ? True or False (if False, Kraken2 will be used)
use_bowtie: False
# folder containing the kraken library for rescue of unmapped reads
kraken_library_unmapped: "/mnt/beegfs/etempez/remapping/kraken_libraries/k2protocol_db"

## OPTIONAL (leave empty quotes to automate from the species folder): 
# Bowtie index files folder (optional)
bowtie_index: ""
# kraken library folder (optional)
kraken_library: "/mnt/beegfs/etempez/remapping/benchmark/kraken_kefir_library"
