######################
### DATA TO MODIFY ###
######################
##### Input files #####
# fastq files to analyse (leave r2 quotes empty if unpaired)
r1: "/mnt/beegfs/projet-kefir/data_illumina/mcf/NG-32390_MCF_10h_lib666597_10168_3_1.fastq.gz"
r2: "/mnt/beegfs/projet-kefir/data_illumina/mcf/NG-32390_MCF_10h_lib666597_10168_3_2.fastq.gz"
# read length
read_lg: 151

# species folder : should only contain <speciesname>.fa or <speciesname>.fasta file for each species
folder_species: "/mnt/beegfs/projet-kefir/metagenome/"


##### Output infos #####
# output folder (leave empty quotes if you want the output in the folder from which you are launching the snakemake command line)
output_folder: "/mnt/beegfs/etempez/remapping/bowtie_paired/"
# build name : name of the metagenome version
build_name: "final_lib"


##### Configuration #####
# name of folder with all .yml files + the metagenome_ncbi_id.txt file
config_folder: "/trinity/home/etempez/remapping_scripts/config_files"


##### Bowtie and Kraken #####
# should we use Bowtie2 for mapping ? True or False (if False, Kraken2 will be used)
use_bowtie: False
# folder containing the kraken library for rescue of unmapped reads
kraken_library_unmapped: "/mnt/beegfs/projet-kefir/kraken_libraries/k2protocol_db"

## OPTIONAL (leave empty quotes to automate from the species folder): 
# Bowtie index files folder
bowtie_index: ""
# kraken library folder
kraken_library: "/mnt/beegfs/projet-kefir/kraken_libraries/metagenome"
