######################
### DATA TO MODIFY ###
######################
# fastq file to analyse
r1: "/mnt/beegfs/etempez/remapping/cinetique_illu_test/DON_test_R1.fastq.gz"
r2: "/mnt/beegfs/etempez/remapping/cinetique_illu_test/DON_test_R2.fastq.gz"
# read length
read_lg: 151

# species folder : for each species, should contain <speciesname>.fa or <speciesname>.fasta file
folder_species: "/mnt/beegfs/etempez/remapping/genome/"

# output folder (leave empty quotes if you want the output in the folder from which you are launching the snakemake command line)
output_folder: "/mnt/beegfs/etempez/remapping/outputs/"

# build name : name of the metagenome version
build_name: "librairie_finale"